// Code generated by go-swagger; DO NOT EDIT.

package contexts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteContextParams creates a new DeleteContextParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteContextParams() *DeleteContextParams {
	return &DeleteContextParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteContextParamsWithTimeout creates a new DeleteContextParams object
// with the ability to set a timeout on a request.
func NewDeleteContextParamsWithTimeout(timeout time.Duration) *DeleteContextParams {
	return &DeleteContextParams{
		timeout: timeout,
	}
}

// NewDeleteContextParamsWithContext creates a new DeleteContextParams object
// with the ability to set a context for a request.
func NewDeleteContextParamsWithContext(ctx context.Context) *DeleteContextParams {
	return &DeleteContextParams{
		Context: ctx,
	}
}

// NewDeleteContextParamsWithHTTPClient creates a new DeleteContextParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteContextParamsWithHTTPClient(client *http.Client) *DeleteContextParams {
	return &DeleteContextParams{
		HTTPClient: client,
	}
}

/*
DeleteContextParams contains all the parameters to send to the API endpoint

	for the delete context operation.

	Typically these are written to a http.Request.
*/
type DeleteContextParams struct {

	/* ID.

	   ID of the context

	   Format: uuid
	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete context params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteContextParams) WithDefaults() *DeleteContextParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete context params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteContextParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete context params
func (o *DeleteContextParams) WithTimeout(timeout time.Duration) *DeleteContextParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete context params
func (o *DeleteContextParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete context params
func (o *DeleteContextParams) WithContext(ctx context.Context) *DeleteContextParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete context params
func (o *DeleteContextParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete context params
func (o *DeleteContextParams) WithHTTPClient(client *http.Client) *DeleteContextParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete context params
func (o *DeleteContextParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete context params
func (o *DeleteContextParams) WithID(id strfmt.UUID) *DeleteContextParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete context params
func (o *DeleteContextParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteContextParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
