// Code generated by go-swagger; DO NOT EDIT.

package contexts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetContextParams creates a new GetContextParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetContextParams() *GetContextParams {
	return &GetContextParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetContextParamsWithTimeout creates a new GetContextParams object
// with the ability to set a timeout on a request.
func NewGetContextParamsWithTimeout(timeout time.Duration) *GetContextParams {
	return &GetContextParams{
		timeout: timeout,
	}
}

// NewGetContextParamsWithContext creates a new GetContextParams object
// with the ability to set a context for a request.
func NewGetContextParamsWithContext(ctx context.Context) *GetContextParams {
	return &GetContextParams{
		Context: ctx,
	}
}

// NewGetContextParamsWithHTTPClient creates a new GetContextParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetContextParamsWithHTTPClient(client *http.Client) *GetContextParams {
	return &GetContextParams{
		HTTPClient: client,
	}
}

/*
GetContextParams contains all the parameters to send to the API endpoint

	for the get context operation.

	Typically these are written to a http.Request.
*/
type GetContextParams struct {

	/* ID.

	   The unique ID of the context.

	   Format: uuid
	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get context params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetContextParams) WithDefaults() *GetContextParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get context params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetContextParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get context params
func (o *GetContextParams) WithTimeout(timeout time.Duration) *GetContextParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get context params
func (o *GetContextParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get context params
func (o *GetContextParams) WithContext(ctx context.Context) *GetContextParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get context params
func (o *GetContextParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get context params
func (o *GetContextParams) WithHTTPClient(client *http.Client) *GetContextParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get context params
func (o *GetContextParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get context params
func (o *GetContextParams) WithID(id strfmt.UUID) *GetContextParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get context params
func (o *GetContextParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetContextParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
