// Code generated by go-swagger; DO NOT EDIT.

package contexts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListContextEnvVarsParams creates a new ListContextEnvVarsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListContextEnvVarsParams() *ListContextEnvVarsParams {
	return &ListContextEnvVarsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListContextEnvVarsParamsWithTimeout creates a new ListContextEnvVarsParams object
// with the ability to set a timeout on a request.
func NewListContextEnvVarsParamsWithTimeout(timeout time.Duration) *ListContextEnvVarsParams {
	return &ListContextEnvVarsParams{
		timeout: timeout,
	}
}

// NewListContextEnvVarsParamsWithContext creates a new ListContextEnvVarsParams object
// with the ability to set a context for a request.
func NewListContextEnvVarsParamsWithContext(ctx context.Context) *ListContextEnvVarsParams {
	return &ListContextEnvVarsParams{
		Context: ctx,
	}
}

// NewListContextEnvVarsParamsWithHTTPClient creates a new ListContextEnvVarsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListContextEnvVarsParamsWithHTTPClient(client *http.Client) *ListContextEnvVarsParams {
	return &ListContextEnvVarsParams{
		HTTPClient: client,
	}
}

/*
ListContextEnvVarsParams contains all the parameters to send to the API endpoint

	for the list context env vars operation.

	Typically these are written to a http.Request.
*/
type ListContextEnvVarsParams struct {

	/* ID.

	   ID of the context

	   Format: uuid
	*/
	ID strfmt.UUID

	/* PageToken.

	   A token to retrieve the next page of results
	*/
	PageToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list context env vars params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListContextEnvVarsParams) WithDefaults() *ListContextEnvVarsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list context env vars params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListContextEnvVarsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list context env vars params
func (o *ListContextEnvVarsParams) WithTimeout(timeout time.Duration) *ListContextEnvVarsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list context env vars params
func (o *ListContextEnvVarsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list context env vars params
func (o *ListContextEnvVarsParams) WithContext(ctx context.Context) *ListContextEnvVarsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list context env vars params
func (o *ListContextEnvVarsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list context env vars params
func (o *ListContextEnvVarsParams) WithHTTPClient(client *http.Client) *ListContextEnvVarsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list context env vars params
func (o *ListContextEnvVarsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the list context env vars params
func (o *ListContextEnvVarsParams) WithID(id strfmt.UUID) *ListContextEnvVarsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the list context env vars params
func (o *ListContextEnvVarsParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WithPageToken adds the pageToken to the list context env vars params
func (o *ListContextEnvVarsParams) WithPageToken(pageToken *string) *ListContextEnvVarsParams {
	o.SetPageToken(pageToken)
	return o
}

// SetPageToken adds the pageToken to the list context env vars params
func (o *ListContextEnvVarsParams) SetPageToken(pageToken *string) {
	o.PageToken = pageToken
}

// WriteToRequest writes these params to a swagger request
func (o *ListContextEnvVarsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if o.PageToken != nil {

		// query param page-token
		var qrPageToken string

		if o.PageToken != nil {
			qrPageToken = *o.PageToken
		}
		qPageToken := qrPageToken
		if qPageToken != "" {

			if err := r.SetQueryParam("page-token", qPageToken); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
