// Code generated by go-swagger; DO NOT EDIT.

package oidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteOrgLevelClaimsParams creates a new DeleteOrgLevelClaimsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteOrgLevelClaimsParams() *DeleteOrgLevelClaimsParams {
	return &DeleteOrgLevelClaimsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOrgLevelClaimsParamsWithTimeout creates a new DeleteOrgLevelClaimsParams object
// with the ability to set a timeout on a request.
func NewDeleteOrgLevelClaimsParamsWithTimeout(timeout time.Duration) *DeleteOrgLevelClaimsParams {
	return &DeleteOrgLevelClaimsParams{
		timeout: timeout,
	}
}

// NewDeleteOrgLevelClaimsParamsWithContext creates a new DeleteOrgLevelClaimsParams object
// with the ability to set a context for a request.
func NewDeleteOrgLevelClaimsParamsWithContext(ctx context.Context) *DeleteOrgLevelClaimsParams {
	return &DeleteOrgLevelClaimsParams{
		Context: ctx,
	}
}

// NewDeleteOrgLevelClaimsParamsWithHTTPClient creates a new DeleteOrgLevelClaimsParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteOrgLevelClaimsParamsWithHTTPClient(client *http.Client) *DeleteOrgLevelClaimsParams {
	return &DeleteOrgLevelClaimsParams{
		HTTPClient: client,
	}
}

/*
DeleteOrgLevelClaimsParams contains all the parameters to send to the API endpoint

	for the delete org level claims operation.

	Typically these are written to a http.Request.
*/
type DeleteOrgLevelClaimsParams struct {

	/* Claims.

	   Comma-separated ist of claims to delete. Valid values are ttl, audience
	*/
	Claims string

	/* OrgID.

	   The unique ID of the organization.

	   Format: uuid
	*/
	OrgID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete org level claims params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteOrgLevelClaimsParams) WithDefaults() *DeleteOrgLevelClaimsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete org level claims params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteOrgLevelClaimsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete org level claims params
func (o *DeleteOrgLevelClaimsParams) WithTimeout(timeout time.Duration) *DeleteOrgLevelClaimsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete org level claims params
func (o *DeleteOrgLevelClaimsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete org level claims params
func (o *DeleteOrgLevelClaimsParams) WithContext(ctx context.Context) *DeleteOrgLevelClaimsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete org level claims params
func (o *DeleteOrgLevelClaimsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete org level claims params
func (o *DeleteOrgLevelClaimsParams) WithHTTPClient(client *http.Client) *DeleteOrgLevelClaimsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete org level claims params
func (o *DeleteOrgLevelClaimsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClaims adds the claims to the delete org level claims params
func (o *DeleteOrgLevelClaimsParams) WithClaims(claims string) *DeleteOrgLevelClaimsParams {
	o.SetClaims(claims)
	return o
}

// SetClaims adds the claims to the delete org level claims params
func (o *DeleteOrgLevelClaimsParams) SetClaims(claims string) {
	o.Claims = claims
}

// WithOrgID adds the orgID to the delete org level claims params
func (o *DeleteOrgLevelClaimsParams) WithOrgID(orgID strfmt.UUID) *DeleteOrgLevelClaimsParams {
	o.SetOrgID(orgID)
	return o
}

// SetOrgID adds the orgId to the delete org level claims params
func (o *DeleteOrgLevelClaimsParams) SetOrgID(orgID strfmt.UUID) {
	o.OrgID = orgID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOrgLevelClaimsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param claims
	qrClaims := o.Claims
	qClaims := qrClaims
	if qClaims != "" {

		if err := r.SetQueryParam("claims", qClaims); err != nil {
			return err
		}
	}

	// path param org-id
	if err := r.SetPathParam("org-id", o.OrgID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
