// Code generated by go-swagger; DO NOT EDIT.

package oidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOrgLevelClaimsParams creates a new GetOrgLevelClaimsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrgLevelClaimsParams() *GetOrgLevelClaimsParams {
	return &GetOrgLevelClaimsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrgLevelClaimsParamsWithTimeout creates a new GetOrgLevelClaimsParams object
// with the ability to set a timeout on a request.
func NewGetOrgLevelClaimsParamsWithTimeout(timeout time.Duration) *GetOrgLevelClaimsParams {
	return &GetOrgLevelClaimsParams{
		timeout: timeout,
	}
}

// NewGetOrgLevelClaimsParamsWithContext creates a new GetOrgLevelClaimsParams object
// with the ability to set a context for a request.
func NewGetOrgLevelClaimsParamsWithContext(ctx context.Context) *GetOrgLevelClaimsParams {
	return &GetOrgLevelClaimsParams{
		Context: ctx,
	}
}

// NewGetOrgLevelClaimsParamsWithHTTPClient creates a new GetOrgLevelClaimsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrgLevelClaimsParamsWithHTTPClient(client *http.Client) *GetOrgLevelClaimsParams {
	return &GetOrgLevelClaimsParams{
		HTTPClient: client,
	}
}

/*
GetOrgLevelClaimsParams contains all the parameters to send to the API endpoint

	for the get org level claims operation.

	Typically these are written to a http.Request.
*/
type GetOrgLevelClaimsParams struct {

	/* OrgID.

	   The unique ID of the organization.

	   Format: uuid
	*/
	OrgID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get org level claims params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrgLevelClaimsParams) WithDefaults() *GetOrgLevelClaimsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get org level claims params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrgLevelClaimsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get org level claims params
func (o *GetOrgLevelClaimsParams) WithTimeout(timeout time.Duration) *GetOrgLevelClaimsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get org level claims params
func (o *GetOrgLevelClaimsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get org level claims params
func (o *GetOrgLevelClaimsParams) WithContext(ctx context.Context) *GetOrgLevelClaimsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get org level claims params
func (o *GetOrgLevelClaimsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get org level claims params
func (o *GetOrgLevelClaimsParams) WithHTTPClient(client *http.Client) *GetOrgLevelClaimsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get org level claims params
func (o *GetOrgLevelClaimsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgID adds the orgID to the get org level claims params
func (o *GetOrgLevelClaimsParams) WithOrgID(orgID strfmt.UUID) *GetOrgLevelClaimsParams {
	o.SetOrgID(orgID)
	return o
}

// SetOrgID adds the orgId to the get org level claims params
func (o *GetOrgLevelClaimsParams) SetOrgID(orgID strfmt.UUID) {
	o.OrgID = orgID
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrgLevelClaimsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param org-id
	if err := r.SetPathParam("org-id", o.OrgID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
