// Code generated by go-swagger; DO NOT EDIT.

package oidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProjectLevelClaimsParams creates a new GetProjectLevelClaimsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectLevelClaimsParams() *GetProjectLevelClaimsParams {
	return &GetProjectLevelClaimsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectLevelClaimsParamsWithTimeout creates a new GetProjectLevelClaimsParams object
// with the ability to set a timeout on a request.
func NewGetProjectLevelClaimsParamsWithTimeout(timeout time.Duration) *GetProjectLevelClaimsParams {
	return &GetProjectLevelClaimsParams{
		timeout: timeout,
	}
}

// NewGetProjectLevelClaimsParamsWithContext creates a new GetProjectLevelClaimsParams object
// with the ability to set a context for a request.
func NewGetProjectLevelClaimsParamsWithContext(ctx context.Context) *GetProjectLevelClaimsParams {
	return &GetProjectLevelClaimsParams{
		Context: ctx,
	}
}

// NewGetProjectLevelClaimsParamsWithHTTPClient creates a new GetProjectLevelClaimsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectLevelClaimsParamsWithHTTPClient(client *http.Client) *GetProjectLevelClaimsParams {
	return &GetProjectLevelClaimsParams{
		HTTPClient: client,
	}
}

/*
GetProjectLevelClaimsParams contains all the parameters to send to the API endpoint

	for the get project level claims operation.

	Typically these are written to a http.Request.
*/
type GetProjectLevelClaimsParams struct {

	/* OrgID.

	   The unique ID of the organization.

	   Format: uuid
	*/
	OrgID strfmt.UUID

	/* ProjectID.

	   The unique ID of the project.

	   Format: uuid
	*/
	ProjectID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get project level claims params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectLevelClaimsParams) WithDefaults() *GetProjectLevelClaimsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project level claims params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectLevelClaimsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project level claims params
func (o *GetProjectLevelClaimsParams) WithTimeout(timeout time.Duration) *GetProjectLevelClaimsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project level claims params
func (o *GetProjectLevelClaimsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get project level claims params
func (o *GetProjectLevelClaimsParams) WithContext(ctx context.Context) *GetProjectLevelClaimsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project level claims params
func (o *GetProjectLevelClaimsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get project level claims params
func (o *GetProjectLevelClaimsParams) WithHTTPClient(client *http.Client) *GetProjectLevelClaimsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project level claims params
func (o *GetProjectLevelClaimsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgID adds the orgID to the get project level claims params
func (o *GetProjectLevelClaimsParams) WithOrgID(orgID strfmt.UUID) *GetProjectLevelClaimsParams {
	o.SetOrgID(orgID)
	return o
}

// SetOrgID adds the orgId to the get project level claims params
func (o *GetProjectLevelClaimsParams) SetOrgID(orgID strfmt.UUID) {
	o.OrgID = orgID
}

// WithProjectID adds the projectID to the get project level claims params
func (o *GetProjectLevelClaimsParams) WithProjectID(projectID strfmt.UUID) *GetProjectLevelClaimsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get project level claims params
func (o *GetProjectLevelClaimsParams) SetProjectID(projectID strfmt.UUID) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectLevelClaimsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param org-id
	if err := r.SetPathParam("org-id", o.OrgID.String()); err != nil {
		return err
	}

	// path param project-id
	if err := r.SetPathParam("project-id", o.ProjectID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
