// Code generated by go-swagger; DO NOT EDIT.

package oidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kelvintaywl/circleci-go-sdk/models"
)

// NewPatchOrgLevelClaimsParams creates a new PatchOrgLevelClaimsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchOrgLevelClaimsParams() *PatchOrgLevelClaimsParams {
	return &PatchOrgLevelClaimsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchOrgLevelClaimsParamsWithTimeout creates a new PatchOrgLevelClaimsParams object
// with the ability to set a timeout on a request.
func NewPatchOrgLevelClaimsParamsWithTimeout(timeout time.Duration) *PatchOrgLevelClaimsParams {
	return &PatchOrgLevelClaimsParams{
		timeout: timeout,
	}
}

// NewPatchOrgLevelClaimsParamsWithContext creates a new PatchOrgLevelClaimsParams object
// with the ability to set a context for a request.
func NewPatchOrgLevelClaimsParamsWithContext(ctx context.Context) *PatchOrgLevelClaimsParams {
	return &PatchOrgLevelClaimsParams{
		Context: ctx,
	}
}

// NewPatchOrgLevelClaimsParamsWithHTTPClient creates a new PatchOrgLevelClaimsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchOrgLevelClaimsParamsWithHTTPClient(client *http.Client) *PatchOrgLevelClaimsParams {
	return &PatchOrgLevelClaimsParams{
		HTTPClient: client,
	}
}

/*
PatchOrgLevelClaimsParams contains all the parameters to send to the API endpoint

	for the patch org level claims operation.

	Typically these are written to a http.Request.
*/
type PatchOrgLevelClaimsParams struct {

	/* Body.

	   Claims information (payload)
	*/
	Body *models.OrgLevelClaimsPayload

	/* OrgID.

	   The unique ID of the organization.

	   Format: uuid
	*/
	OrgID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch org level claims params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchOrgLevelClaimsParams) WithDefaults() *PatchOrgLevelClaimsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch org level claims params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchOrgLevelClaimsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch org level claims params
func (o *PatchOrgLevelClaimsParams) WithTimeout(timeout time.Duration) *PatchOrgLevelClaimsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch org level claims params
func (o *PatchOrgLevelClaimsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch org level claims params
func (o *PatchOrgLevelClaimsParams) WithContext(ctx context.Context) *PatchOrgLevelClaimsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch org level claims params
func (o *PatchOrgLevelClaimsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch org level claims params
func (o *PatchOrgLevelClaimsParams) WithHTTPClient(client *http.Client) *PatchOrgLevelClaimsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch org level claims params
func (o *PatchOrgLevelClaimsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch org level claims params
func (o *PatchOrgLevelClaimsParams) WithBody(body *models.OrgLevelClaimsPayload) *PatchOrgLevelClaimsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch org level claims params
func (o *PatchOrgLevelClaimsParams) SetBody(body *models.OrgLevelClaimsPayload) {
	o.Body = body
}

// WithOrgID adds the orgID to the patch org level claims params
func (o *PatchOrgLevelClaimsParams) WithOrgID(orgID strfmt.UUID) *PatchOrgLevelClaimsParams {
	o.SetOrgID(orgID)
	return o
}

// SetOrgID adds the orgId to the patch org level claims params
func (o *PatchOrgLevelClaimsParams) SetOrgID(orgID strfmt.UUID) {
	o.OrgID = orgID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchOrgLevelClaimsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param org-id
	if err := r.SetPathParam("org-id", o.OrgID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
