// Code generated by go-swagger; DO NOT EDIT.

package oidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kelvintaywl/circleci-go-sdk/models"
)

// NewPatchProjectLevelClaimsParams creates a new PatchProjectLevelClaimsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchProjectLevelClaimsParams() *PatchProjectLevelClaimsParams {
	return &PatchProjectLevelClaimsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchProjectLevelClaimsParamsWithTimeout creates a new PatchProjectLevelClaimsParams object
// with the ability to set a timeout on a request.
func NewPatchProjectLevelClaimsParamsWithTimeout(timeout time.Duration) *PatchProjectLevelClaimsParams {
	return &PatchProjectLevelClaimsParams{
		timeout: timeout,
	}
}

// NewPatchProjectLevelClaimsParamsWithContext creates a new PatchProjectLevelClaimsParams object
// with the ability to set a context for a request.
func NewPatchProjectLevelClaimsParamsWithContext(ctx context.Context) *PatchProjectLevelClaimsParams {
	return &PatchProjectLevelClaimsParams{
		Context: ctx,
	}
}

// NewPatchProjectLevelClaimsParamsWithHTTPClient creates a new PatchProjectLevelClaimsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchProjectLevelClaimsParamsWithHTTPClient(client *http.Client) *PatchProjectLevelClaimsParams {
	return &PatchProjectLevelClaimsParams{
		HTTPClient: client,
	}
}

/*
PatchProjectLevelClaimsParams contains all the parameters to send to the API endpoint

	for the patch project level claims operation.

	Typically these are written to a http.Request.
*/
type PatchProjectLevelClaimsParams struct {

	/* Body.

	   Claims information (payload)
	*/
	Body *models.ProjectLevelClaimsPayload

	/* OrgID.

	   The unique ID of the organization.

	   Format: uuid
	*/
	OrgID strfmt.UUID

	/* ProjectID.

	   The unique ID of the project.

	   Format: uuid
	*/
	ProjectID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch project level claims params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchProjectLevelClaimsParams) WithDefaults() *PatchProjectLevelClaimsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch project level claims params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchProjectLevelClaimsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch project level claims params
func (o *PatchProjectLevelClaimsParams) WithTimeout(timeout time.Duration) *PatchProjectLevelClaimsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch project level claims params
func (o *PatchProjectLevelClaimsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch project level claims params
func (o *PatchProjectLevelClaimsParams) WithContext(ctx context.Context) *PatchProjectLevelClaimsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch project level claims params
func (o *PatchProjectLevelClaimsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch project level claims params
func (o *PatchProjectLevelClaimsParams) WithHTTPClient(client *http.Client) *PatchProjectLevelClaimsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch project level claims params
func (o *PatchProjectLevelClaimsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch project level claims params
func (o *PatchProjectLevelClaimsParams) WithBody(body *models.ProjectLevelClaimsPayload) *PatchProjectLevelClaimsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch project level claims params
func (o *PatchProjectLevelClaimsParams) SetBody(body *models.ProjectLevelClaimsPayload) {
	o.Body = body
}

// WithOrgID adds the orgID to the patch project level claims params
func (o *PatchProjectLevelClaimsParams) WithOrgID(orgID strfmt.UUID) *PatchProjectLevelClaimsParams {
	o.SetOrgID(orgID)
	return o
}

// SetOrgID adds the orgId to the patch project level claims params
func (o *PatchProjectLevelClaimsParams) SetOrgID(orgID strfmt.UUID) {
	o.OrgID = orgID
}

// WithProjectID adds the projectID to the patch project level claims params
func (o *PatchProjectLevelClaimsParams) WithProjectID(projectID strfmt.UUID) *PatchProjectLevelClaimsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the patch project level claims params
func (o *PatchProjectLevelClaimsParams) SetProjectID(projectID strfmt.UUID) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchProjectLevelClaimsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param org-id
	if err := r.SetPathParam("org-id", o.OrgID.String()); err != nil {
		return err
	}

	// path param project-id
	if err := r.SetPathParam("project-id", o.ProjectID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
