// Code generated by go-swagger; DO NOT EDIT.

package project_envvar

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kelvintaywl/circleci-go-sdk/models"
)

// NewAddProjectEnvVarParams creates a new AddProjectEnvVarParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddProjectEnvVarParams() *AddProjectEnvVarParams {
	return &AddProjectEnvVarParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddProjectEnvVarParamsWithTimeout creates a new AddProjectEnvVarParams object
// with the ability to set a timeout on a request.
func NewAddProjectEnvVarParamsWithTimeout(timeout time.Duration) *AddProjectEnvVarParams {
	return &AddProjectEnvVarParams{
		timeout: timeout,
	}
}

// NewAddProjectEnvVarParamsWithContext creates a new AddProjectEnvVarParams object
// with the ability to set a context for a request.
func NewAddProjectEnvVarParamsWithContext(ctx context.Context) *AddProjectEnvVarParams {
	return &AddProjectEnvVarParams{
		Context: ctx,
	}
}

// NewAddProjectEnvVarParamsWithHTTPClient creates a new AddProjectEnvVarParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddProjectEnvVarParamsWithHTTPClient(client *http.Client) *AddProjectEnvVarParams {
	return &AddProjectEnvVarParams{
		HTTPClient: client,
	}
}

/*
AddProjectEnvVarParams contains all the parameters to send to the API endpoint

	for the add project env var operation.

	Typically these are written to a http.Request.
*/
type AddProjectEnvVarParams struct {

	/* Body.

	   Environment variable information (payload)
	*/
	Body *models.ProjectEnvVarPayload

	/* ProjectSlug.

	     Project slug in the form vcs-slug/org-name/repo-name.
	The / characters may be URL-escaped.
	Example: gh/CircleCI-Public/api-preview-docs

	*/
	ProjectSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add project env var params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddProjectEnvVarParams) WithDefaults() *AddProjectEnvVarParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add project env var params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddProjectEnvVarParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add project env var params
func (o *AddProjectEnvVarParams) WithTimeout(timeout time.Duration) *AddProjectEnvVarParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add project env var params
func (o *AddProjectEnvVarParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add project env var params
func (o *AddProjectEnvVarParams) WithContext(ctx context.Context) *AddProjectEnvVarParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add project env var params
func (o *AddProjectEnvVarParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add project env var params
func (o *AddProjectEnvVarParams) WithHTTPClient(client *http.Client) *AddProjectEnvVarParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add project env var params
func (o *AddProjectEnvVarParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add project env var params
func (o *AddProjectEnvVarParams) WithBody(body *models.ProjectEnvVarPayload) *AddProjectEnvVarParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add project env var params
func (o *AddProjectEnvVarParams) SetBody(body *models.ProjectEnvVarPayload) {
	o.Body = body
}

// WithProjectSlug adds the projectSlug to the add project env var params
func (o *AddProjectEnvVarParams) WithProjectSlug(projectSlug string) *AddProjectEnvVarParams {
	o.SetProjectSlug(projectSlug)
	return o
}

// SetProjectSlug adds the projectSlug to the add project env var params
func (o *AddProjectEnvVarParams) SetProjectSlug(projectSlug string) {
	o.ProjectSlug = projectSlug
}

// WriteToRequest writes these params to a swagger request
func (o *AddProjectEnvVarParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param project-slug
	if err := r.SetPathParam("project-slug", o.ProjectSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
