// Code generated by go-swagger; DO NOT EDIT.

package project_envvar

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProjectEnvVarParams creates a new GetProjectEnvVarParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectEnvVarParams() *GetProjectEnvVarParams {
	return &GetProjectEnvVarParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectEnvVarParamsWithTimeout creates a new GetProjectEnvVarParams object
// with the ability to set a timeout on a request.
func NewGetProjectEnvVarParamsWithTimeout(timeout time.Duration) *GetProjectEnvVarParams {
	return &GetProjectEnvVarParams{
		timeout: timeout,
	}
}

// NewGetProjectEnvVarParamsWithContext creates a new GetProjectEnvVarParams object
// with the ability to set a context for a request.
func NewGetProjectEnvVarParamsWithContext(ctx context.Context) *GetProjectEnvVarParams {
	return &GetProjectEnvVarParams{
		Context: ctx,
	}
}

// NewGetProjectEnvVarParamsWithHTTPClient creates a new GetProjectEnvVarParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectEnvVarParamsWithHTTPClient(client *http.Client) *GetProjectEnvVarParams {
	return &GetProjectEnvVarParams{
		HTTPClient: client,
	}
}

/*
GetProjectEnvVarParams contains all the parameters to send to the API endpoint

	for the get project env var operation.

	Typically these are written to a http.Request.
*/
type GetProjectEnvVarParams struct {

	/* Name.

	   The name of the environment variable.
	*/
	Name string

	/* ProjectSlug.

	     Project slug in the form vcs-slug/org-name/repo-name.
	The / characters may be URL-escaped.
	Example: gh/CircleCI-Public/api-preview-docs

	*/
	ProjectSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get project env var params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectEnvVarParams) WithDefaults() *GetProjectEnvVarParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project env var params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectEnvVarParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project env var params
func (o *GetProjectEnvVarParams) WithTimeout(timeout time.Duration) *GetProjectEnvVarParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project env var params
func (o *GetProjectEnvVarParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get project env var params
func (o *GetProjectEnvVarParams) WithContext(ctx context.Context) *GetProjectEnvVarParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project env var params
func (o *GetProjectEnvVarParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get project env var params
func (o *GetProjectEnvVarParams) WithHTTPClient(client *http.Client) *GetProjectEnvVarParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project env var params
func (o *GetProjectEnvVarParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get project env var params
func (o *GetProjectEnvVarParams) WithName(name string) *GetProjectEnvVarParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get project env var params
func (o *GetProjectEnvVarParams) SetName(name string) {
	o.Name = name
}

// WithProjectSlug adds the projectSlug to the get project env var params
func (o *GetProjectEnvVarParams) WithProjectSlug(projectSlug string) *GetProjectEnvVarParams {
	o.SetProjectSlug(projectSlug)
	return o
}

// SetProjectSlug adds the projectSlug to the get project env var params
func (o *GetProjectEnvVarParams) SetProjectSlug(projectSlug string) {
	o.ProjectSlug = projectSlug
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectEnvVarParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param project-slug
	if err := r.SetPathParam("project-slug", o.ProjectSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
