// Code generated by go-swagger; DO NOT EDIT.

package schedule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kelvintaywl/circleci-go-sdk/models"
)

// NewAddScheduleParams creates a new AddScheduleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddScheduleParams() *AddScheduleParams {
	return &AddScheduleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddScheduleParamsWithTimeout creates a new AddScheduleParams object
// with the ability to set a timeout on a request.
func NewAddScheduleParamsWithTimeout(timeout time.Duration) *AddScheduleParams {
	return &AddScheduleParams{
		timeout: timeout,
	}
}

// NewAddScheduleParamsWithContext creates a new AddScheduleParams object
// with the ability to set a context for a request.
func NewAddScheduleParamsWithContext(ctx context.Context) *AddScheduleParams {
	return &AddScheduleParams{
		Context: ctx,
	}
}

// NewAddScheduleParamsWithHTTPClient creates a new AddScheduleParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddScheduleParamsWithHTTPClient(client *http.Client) *AddScheduleParams {
	return &AddScheduleParams{
		HTTPClient: client,
	}
}

/*
AddScheduleParams contains all the parameters to send to the API endpoint

	for the add schedule operation.

	Typically these are written to a http.Request.
*/
type AddScheduleParams struct {

	/* Body.

	   Schedule information (payload)
	*/
	Body *models.SchedulePayload

	/* ProjectSlug.

	     Project slug in the form vcs-slug/org-name/repo-name.
	The / characters may be URL-escaped.
	Example: gh/CircleCI-Public/api-preview-docs

	*/
	ProjectSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add schedule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddScheduleParams) WithDefaults() *AddScheduleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add schedule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddScheduleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add schedule params
func (o *AddScheduleParams) WithTimeout(timeout time.Duration) *AddScheduleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add schedule params
func (o *AddScheduleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add schedule params
func (o *AddScheduleParams) WithContext(ctx context.Context) *AddScheduleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add schedule params
func (o *AddScheduleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add schedule params
func (o *AddScheduleParams) WithHTTPClient(client *http.Client) *AddScheduleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add schedule params
func (o *AddScheduleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add schedule params
func (o *AddScheduleParams) WithBody(body *models.SchedulePayload) *AddScheduleParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add schedule params
func (o *AddScheduleParams) SetBody(body *models.SchedulePayload) {
	o.Body = body
}

// WithProjectSlug adds the projectSlug to the add schedule params
func (o *AddScheduleParams) WithProjectSlug(projectSlug string) *AddScheduleParams {
	o.SetProjectSlug(projectSlug)
	return o
}

// SetProjectSlug adds the projectSlug to the add schedule params
func (o *AddScheduleParams) SetProjectSlug(projectSlug string) {
	o.ProjectSlug = projectSlug
}

// WriteToRequest writes these params to a swagger request
func (o *AddScheduleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param project-slug
	if err := r.SetPathParam("project-slug", o.ProjectSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
