// Code generated by go-swagger; DO NOT EDIT.

package schedule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetScheduleParams creates a new GetScheduleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetScheduleParams() *GetScheduleParams {
	return &GetScheduleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetScheduleParamsWithTimeout creates a new GetScheduleParams object
// with the ability to set a timeout on a request.
func NewGetScheduleParamsWithTimeout(timeout time.Duration) *GetScheduleParams {
	return &GetScheduleParams{
		timeout: timeout,
	}
}

// NewGetScheduleParamsWithContext creates a new GetScheduleParams object
// with the ability to set a context for a request.
func NewGetScheduleParamsWithContext(ctx context.Context) *GetScheduleParams {
	return &GetScheduleParams{
		Context: ctx,
	}
}

// NewGetScheduleParamsWithHTTPClient creates a new GetScheduleParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetScheduleParamsWithHTTPClient(client *http.Client) *GetScheduleParams {
	return &GetScheduleParams{
		HTTPClient: client,
	}
}

/*
GetScheduleParams contains all the parameters to send to the API endpoint

	for the get schedule operation.

	Typically these are written to a http.Request.
*/
type GetScheduleParams struct {

	/* ID.

	   The unique ID of the schedule.

	   Format: uuid
	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get schedule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetScheduleParams) WithDefaults() *GetScheduleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get schedule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetScheduleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get schedule params
func (o *GetScheduleParams) WithTimeout(timeout time.Duration) *GetScheduleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get schedule params
func (o *GetScheduleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get schedule params
func (o *GetScheduleParams) WithContext(ctx context.Context) *GetScheduleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get schedule params
func (o *GetScheduleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get schedule params
func (o *GetScheduleParams) WithHTTPClient(client *http.Client) *GetScheduleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get schedule params
func (o *GetScheduleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get schedule params
func (o *GetScheduleParams) WithID(id strfmt.UUID) *GetScheduleParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get schedule params
func (o *GetScheduleParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetScheduleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
