// Code generated by go-swagger; DO NOT EDIT.

package schedule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kelvintaywl/circleci-go-sdk/models"
)

// ListSchedulesReader is a Reader for the ListSchedules structure.
type ListSchedulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSchedulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListSchedulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListSchedulesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListSchedulesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListSchedulesOK creates a ListSchedulesOK with default headers values
func NewListSchedulesOK() *ListSchedulesOK {
	return &ListSchedulesOK{}
}

/*
ListSchedulesOK describes a response with status code 200, with default header values.

A sequence of schedules
*/
type ListSchedulesOK struct {
	Payload *models.SchedulesInfo
}

// IsSuccess returns true when this list schedules o k response has a 2xx status code
func (o *ListSchedulesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list schedules o k response has a 3xx status code
func (o *ListSchedulesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list schedules o k response has a 4xx status code
func (o *ListSchedulesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list schedules o k response has a 5xx status code
func (o *ListSchedulesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list schedules o k response a status code equal to that given
func (o *ListSchedulesOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListSchedulesOK) Error() string {
	return fmt.Sprintf("[GET /project/{project-slug}/schedule][%d] listSchedulesOK  %+v", 200, o.Payload)
}

func (o *ListSchedulesOK) String() string {
	return fmt.Sprintf("[GET /project/{project-slug}/schedule][%d] listSchedulesOK  %+v", 200, o.Payload)
}

func (o *ListSchedulesOK) GetPayload() *models.SchedulesInfo {
	return o.Payload
}

func (o *ListSchedulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SchedulesInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSchedulesBadRequest creates a ListSchedulesBadRequest with default headers values
func NewListSchedulesBadRequest() *ListSchedulesBadRequest {
	return &ListSchedulesBadRequest{}
}

/*
ListSchedulesBadRequest describes a response with status code 400, with default header values.

Invalid input
*/
type ListSchedulesBadRequest struct {
	Payload *models.Errored
}

// IsSuccess returns true when this list schedules bad request response has a 2xx status code
func (o *ListSchedulesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list schedules bad request response has a 3xx status code
func (o *ListSchedulesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list schedules bad request response has a 4xx status code
func (o *ListSchedulesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list schedules bad request response has a 5xx status code
func (o *ListSchedulesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list schedules bad request response a status code equal to that given
func (o *ListSchedulesBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ListSchedulesBadRequest) Error() string {
	return fmt.Sprintf("[GET /project/{project-slug}/schedule][%d] listSchedulesBadRequest  %+v", 400, o.Payload)
}

func (o *ListSchedulesBadRequest) String() string {
	return fmt.Sprintf("[GET /project/{project-slug}/schedule][%d] listSchedulesBadRequest  %+v", 400, o.Payload)
}

func (o *ListSchedulesBadRequest) GetPayload() *models.Errored {
	return o.Payload
}

func (o *ListSchedulesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errored)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSchedulesNotFound creates a ListSchedulesNotFound with default headers values
func NewListSchedulesNotFound() *ListSchedulesNotFound {
	return &ListSchedulesNotFound{}
}

/*
ListSchedulesNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ListSchedulesNotFound struct {
	Payload *models.Errored
}

// IsSuccess returns true when this list schedules not found response has a 2xx status code
func (o *ListSchedulesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list schedules not found response has a 3xx status code
func (o *ListSchedulesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list schedules not found response has a 4xx status code
func (o *ListSchedulesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this list schedules not found response has a 5xx status code
func (o *ListSchedulesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this list schedules not found response a status code equal to that given
func (o *ListSchedulesNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *ListSchedulesNotFound) Error() string {
	return fmt.Sprintf("[GET /project/{project-slug}/schedule][%d] listSchedulesNotFound  %+v", 404, o.Payload)
}

func (o *ListSchedulesNotFound) String() string {
	return fmt.Sprintf("[GET /project/{project-slug}/schedule][%d] listSchedulesNotFound  %+v", 404, o.Payload)
}

func (o *ListSchedulesNotFound) GetPayload() *models.Errored {
	return o.Payload
}

func (o *ListSchedulesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errored)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
