// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kelvintaywl/circleci-go-sdk/models"
)

// NewAddProjectCheckoutKeyParams creates a new AddProjectCheckoutKeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddProjectCheckoutKeyParams() *AddProjectCheckoutKeyParams {
	return &AddProjectCheckoutKeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddProjectCheckoutKeyParamsWithTimeout creates a new AddProjectCheckoutKeyParams object
// with the ability to set a timeout on a request.
func NewAddProjectCheckoutKeyParamsWithTimeout(timeout time.Duration) *AddProjectCheckoutKeyParams {
	return &AddProjectCheckoutKeyParams{
		timeout: timeout,
	}
}

// NewAddProjectCheckoutKeyParamsWithContext creates a new AddProjectCheckoutKeyParams object
// with the ability to set a context for a request.
func NewAddProjectCheckoutKeyParamsWithContext(ctx context.Context) *AddProjectCheckoutKeyParams {
	return &AddProjectCheckoutKeyParams{
		Context: ctx,
	}
}

// NewAddProjectCheckoutKeyParamsWithHTTPClient creates a new AddProjectCheckoutKeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddProjectCheckoutKeyParamsWithHTTPClient(client *http.Client) *AddProjectCheckoutKeyParams {
	return &AddProjectCheckoutKeyParams{
		HTTPClient: client,
	}
}

/*
AddProjectCheckoutKeyParams contains all the parameters to send to the API endpoint

	for the add project checkout key operation.

	Typically these are written to a http.Request.
*/
type AddProjectCheckoutKeyParams struct {

	/* Body.

	   checkout key information (payload)
	*/
	Body *models.ProjectCheckoutKeyPayload

	/* ProjectSlug.

	     Project slug in the form vcs-slug/org-name/repo-name.
	The / characters may be URL-escaped.
	Example: gh/CircleCI-Public/api-preview-docs

	*/
	ProjectSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add project checkout key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddProjectCheckoutKeyParams) WithDefaults() *AddProjectCheckoutKeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add project checkout key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddProjectCheckoutKeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add project checkout key params
func (o *AddProjectCheckoutKeyParams) WithTimeout(timeout time.Duration) *AddProjectCheckoutKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add project checkout key params
func (o *AddProjectCheckoutKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add project checkout key params
func (o *AddProjectCheckoutKeyParams) WithContext(ctx context.Context) *AddProjectCheckoutKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add project checkout key params
func (o *AddProjectCheckoutKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add project checkout key params
func (o *AddProjectCheckoutKeyParams) WithHTTPClient(client *http.Client) *AddProjectCheckoutKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add project checkout key params
func (o *AddProjectCheckoutKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add project checkout key params
func (o *AddProjectCheckoutKeyParams) WithBody(body *models.ProjectCheckoutKeyPayload) *AddProjectCheckoutKeyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add project checkout key params
func (o *AddProjectCheckoutKeyParams) SetBody(body *models.ProjectCheckoutKeyPayload) {
	o.Body = body
}

// WithProjectSlug adds the projectSlug to the add project checkout key params
func (o *AddProjectCheckoutKeyParams) WithProjectSlug(projectSlug string) *AddProjectCheckoutKeyParams {
	o.SetProjectSlug(projectSlug)
	return o
}

// SetProjectSlug adds the projectSlug to the add project checkout key params
func (o *AddProjectCheckoutKeyParams) SetProjectSlug(projectSlug string) {
	o.ProjectSlug = projectSlug
}

// WriteToRequest writes these params to a swagger request
func (o *AddProjectCheckoutKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param project-slug
	if err := r.SetPathParam("project-slug", o.ProjectSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
