// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteProjectCheckoutKeyParams creates a new DeleteProjectCheckoutKeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteProjectCheckoutKeyParams() *DeleteProjectCheckoutKeyParams {
	return &DeleteProjectCheckoutKeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteProjectCheckoutKeyParamsWithTimeout creates a new DeleteProjectCheckoutKeyParams object
// with the ability to set a timeout on a request.
func NewDeleteProjectCheckoutKeyParamsWithTimeout(timeout time.Duration) *DeleteProjectCheckoutKeyParams {
	return &DeleteProjectCheckoutKeyParams{
		timeout: timeout,
	}
}

// NewDeleteProjectCheckoutKeyParamsWithContext creates a new DeleteProjectCheckoutKeyParams object
// with the ability to set a context for a request.
func NewDeleteProjectCheckoutKeyParamsWithContext(ctx context.Context) *DeleteProjectCheckoutKeyParams {
	return &DeleteProjectCheckoutKeyParams{
		Context: ctx,
	}
}

// NewDeleteProjectCheckoutKeyParamsWithHTTPClient creates a new DeleteProjectCheckoutKeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteProjectCheckoutKeyParamsWithHTTPClient(client *http.Client) *DeleteProjectCheckoutKeyParams {
	return &DeleteProjectCheckoutKeyParams{
		HTTPClient: client,
	}
}

/*
DeleteProjectCheckoutKeyParams contains all the parameters to send to the API endpoint

	for the delete project checkout key operation.

	Typically these are written to a http.Request.
*/
type DeleteProjectCheckoutKeyParams struct {

	/* Fingerprint.

	   An SSH key fingerprint
	*/
	Fingerprint string

	/* ProjectSlug.

	     Project slug in the form vcs-slug/org-name/repo-name.
	The / characters may be URL-escaped.
	Example: gh/CircleCI-Public/api-preview-docs

	*/
	ProjectSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete project checkout key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectCheckoutKeyParams) WithDefaults() *DeleteProjectCheckoutKeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete project checkout key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectCheckoutKeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete project checkout key params
func (o *DeleteProjectCheckoutKeyParams) WithTimeout(timeout time.Duration) *DeleteProjectCheckoutKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete project checkout key params
func (o *DeleteProjectCheckoutKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete project checkout key params
func (o *DeleteProjectCheckoutKeyParams) WithContext(ctx context.Context) *DeleteProjectCheckoutKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete project checkout key params
func (o *DeleteProjectCheckoutKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete project checkout key params
func (o *DeleteProjectCheckoutKeyParams) WithHTTPClient(client *http.Client) *DeleteProjectCheckoutKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete project checkout key params
func (o *DeleteProjectCheckoutKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFingerprint adds the fingerprint to the delete project checkout key params
func (o *DeleteProjectCheckoutKeyParams) WithFingerprint(fingerprint string) *DeleteProjectCheckoutKeyParams {
	o.SetFingerprint(fingerprint)
	return o
}

// SetFingerprint adds the fingerprint to the delete project checkout key params
func (o *DeleteProjectCheckoutKeyParams) SetFingerprint(fingerprint string) {
	o.Fingerprint = fingerprint
}

// WithProjectSlug adds the projectSlug to the delete project checkout key params
func (o *DeleteProjectCheckoutKeyParams) WithProjectSlug(projectSlug string) *DeleteProjectCheckoutKeyParams {
	o.SetProjectSlug(projectSlug)
	return o
}

// SetProjectSlug adds the projectSlug to the delete project checkout key params
func (o *DeleteProjectCheckoutKeyParams) SetProjectSlug(projectSlug string) {
	o.ProjectSlug = projectSlug
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteProjectCheckoutKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param fingerprint
	if err := r.SetPathParam("fingerprint", o.Fingerprint); err != nil {
		return err
	}

	// path param project-slug
	if err := r.SetPathParam("project-slug", o.ProjectSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
