// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kelvintaywl/circleci-go-sdk/models"
)

// GetProjectReader is a Reader for the GetProject structure.
type GetProjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProjectBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetProjectNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetProjectOK creates a GetProjectOK with default headers values
func NewGetProjectOK() *GetProjectOK {
	return &GetProjectOK{}
}

/*
GetProjectOK describes a response with status code 200, with default header values.

Project information
*/
type GetProjectOK struct {
	Payload *models.ProjectInfo
}

// IsSuccess returns true when this get project o k response has a 2xx status code
func (o *GetProjectOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get project o k response has a 3xx status code
func (o *GetProjectOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project o k response has a 4xx status code
func (o *GetProjectOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project o k response has a 5xx status code
func (o *GetProjectOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get project o k response a status code equal to that given
func (o *GetProjectOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetProjectOK) Error() string {
	return fmt.Sprintf("[GET /project/{project-slug}][%d] getProjectOK  %+v", 200, o.Payload)
}

func (o *GetProjectOK) String() string {
	return fmt.Sprintf("[GET /project/{project-slug}][%d] getProjectOK  %+v", 200, o.Payload)
}

func (o *GetProjectOK) GetPayload() *models.ProjectInfo {
	return o.Payload
}

func (o *GetProjectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProjectInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProjectBadRequest creates a GetProjectBadRequest with default headers values
func NewGetProjectBadRequest() *GetProjectBadRequest {
	return &GetProjectBadRequest{}
}

/*
GetProjectBadRequest describes a response with status code 400, with default header values.

Invalid input
*/
type GetProjectBadRequest struct {
	Payload *models.Errored
}

// IsSuccess returns true when this get project bad request response has a 2xx status code
func (o *GetProjectBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get project bad request response has a 3xx status code
func (o *GetProjectBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project bad request response has a 4xx status code
func (o *GetProjectBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get project bad request response has a 5xx status code
func (o *GetProjectBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get project bad request response a status code equal to that given
func (o *GetProjectBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetProjectBadRequest) Error() string {
	return fmt.Sprintf("[GET /project/{project-slug}][%d] getProjectBadRequest  %+v", 400, o.Payload)
}

func (o *GetProjectBadRequest) String() string {
	return fmt.Sprintf("[GET /project/{project-slug}][%d] getProjectBadRequest  %+v", 400, o.Payload)
}

func (o *GetProjectBadRequest) GetPayload() *models.Errored {
	return o.Payload
}

func (o *GetProjectBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errored)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProjectNotFound creates a GetProjectNotFound with default headers values
func NewGetProjectNotFound() *GetProjectNotFound {
	return &GetProjectNotFound{}
}

/*
GetProjectNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetProjectNotFound struct {
	Payload *models.Errored
}

// IsSuccess returns true when this get project not found response has a 2xx status code
func (o *GetProjectNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get project not found response has a 3xx status code
func (o *GetProjectNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project not found response has a 4xx status code
func (o *GetProjectNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get project not found response has a 5xx status code
func (o *GetProjectNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get project not found response a status code equal to that given
func (o *GetProjectNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetProjectNotFound) Error() string {
	return fmt.Sprintf("[GET /project/{project-slug}][%d] getProjectNotFound  %+v", 404, o.Payload)
}

func (o *GetProjectNotFound) String() string {
	return fmt.Sprintf("[GET /project/{project-slug}][%d] getProjectNotFound  %+v", 404, o.Payload)
}

func (o *GetProjectNotFound) GetPayload() *models.Errored {
	return o.Payload
}

func (o *GetProjectNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errored)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
