// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kelvintaywl/circleci-go-sdk/models"
)

// ListProjectEnvVarsReader is a Reader for the ListProjectEnvVars structure.
type ListProjectEnvVarsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListProjectEnvVarsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListProjectEnvVarsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListProjectEnvVarsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListProjectEnvVarsOK creates a ListProjectEnvVarsOK with default headers values
func NewListProjectEnvVarsOK() *ListProjectEnvVarsOK {
	return &ListProjectEnvVarsOK{}
}

/*
ListProjectEnvVarsOK describes a response with status code 200, with default header values.

A sequence of project environment variables
*/
type ListProjectEnvVarsOK struct {
	Payload *models.ProjectEnvVarsInfo
}

// IsSuccess returns true when this list project env vars o k response has a 2xx status code
func (o *ListProjectEnvVarsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list project env vars o k response has a 3xx status code
func (o *ListProjectEnvVarsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list project env vars o k response has a 4xx status code
func (o *ListProjectEnvVarsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list project env vars o k response has a 5xx status code
func (o *ListProjectEnvVarsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list project env vars o k response a status code equal to that given
func (o *ListProjectEnvVarsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListProjectEnvVarsOK) Error() string {
	return fmt.Sprintf("[GET /project/{project-slug}/envvar][%d] listProjectEnvVarsOK  %+v", 200, o.Payload)
}

func (o *ListProjectEnvVarsOK) String() string {
	return fmt.Sprintf("[GET /project/{project-slug}/envvar][%d] listProjectEnvVarsOK  %+v", 200, o.Payload)
}

func (o *ListProjectEnvVarsOK) GetPayload() *models.ProjectEnvVarsInfo {
	return o.Payload
}

func (o *ListProjectEnvVarsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProjectEnvVarsInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListProjectEnvVarsBadRequest creates a ListProjectEnvVarsBadRequest with default headers values
func NewListProjectEnvVarsBadRequest() *ListProjectEnvVarsBadRequest {
	return &ListProjectEnvVarsBadRequest{}
}

/*
ListProjectEnvVarsBadRequest describes a response with status code 400, with default header values.

Invalid input
*/
type ListProjectEnvVarsBadRequest struct {
	Payload *models.Errored
}

// IsSuccess returns true when this list project env vars bad request response has a 2xx status code
func (o *ListProjectEnvVarsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list project env vars bad request response has a 3xx status code
func (o *ListProjectEnvVarsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list project env vars bad request response has a 4xx status code
func (o *ListProjectEnvVarsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list project env vars bad request response has a 5xx status code
func (o *ListProjectEnvVarsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list project env vars bad request response a status code equal to that given
func (o *ListProjectEnvVarsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ListProjectEnvVarsBadRequest) Error() string {
	return fmt.Sprintf("[GET /project/{project-slug}/envvar][%d] listProjectEnvVarsBadRequest  %+v", 400, o.Payload)
}

func (o *ListProjectEnvVarsBadRequest) String() string {
	return fmt.Sprintf("[GET /project/{project-slug}/envvar][%d] listProjectEnvVarsBadRequest  %+v", 400, o.Payload)
}

func (o *ListProjectEnvVarsBadRequest) GetPayload() *models.Errored {
	return o.Payload
}

func (o *ListProjectEnvVarsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errored)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
