// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new project API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for project API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	AddProjectCheckoutKey(params *AddProjectCheckoutKeyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddProjectCheckoutKeyCreated, error)

	AddProjectEnvVar(params *AddProjectEnvVarParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddProjectEnvVarCreated, error)

	DeleteProjectCheckoutKey(params *DeleteProjectCheckoutKeyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectCheckoutKeyOK, error)

	DeleteProjectEnvVar(params *DeleteProjectEnvVarParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectEnvVarOK, error)

	GetProject(params *GetProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectOK, error)

	GetProjectCheckoutKey(params *GetProjectCheckoutKeyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectCheckoutKeyOK, error)

	GetProjectEnvVar(params *GetProjectEnvVarParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectEnvVarOK, error)

	ListProjectCheckoutKeys(params *ListProjectCheckoutKeysParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListProjectCheckoutKeysOK, error)

	ListProjectEnvVars(params *ListProjectEnvVarsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListProjectEnvVarsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
AddProjectCheckoutKey creates a project checkout key
*/
func (a *Client) AddProjectCheckoutKey(params *AddProjectCheckoutKeyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddProjectCheckoutKeyCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddProjectCheckoutKeyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "AddProjectCheckoutKey",
		Method:             "POST",
		PathPattern:        "/project/{project-slug}/checkout-key",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AddProjectCheckoutKeyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AddProjectCheckoutKeyCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for AddProjectCheckoutKey: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
AddProjectEnvVar creates a project environment variable
*/
func (a *Client) AddProjectEnvVar(params *AddProjectEnvVarParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddProjectEnvVarCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddProjectEnvVarParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "AddProjectEnvVar",
		Method:             "POST",
		PathPattern:        "/project/{project-slug}/envvar",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AddProjectEnvVarReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AddProjectEnvVarCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for AddProjectEnvVar: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteProjectCheckoutKey deletes a project checkout key
*/
func (a *Client) DeleteProjectCheckoutKey(params *DeleteProjectCheckoutKeyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectCheckoutKeyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteProjectCheckoutKeyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteProjectCheckoutKey",
		Method:             "DELETE",
		PathPattern:        "/project/{project-slug}/checkout-key/{fingerprint}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteProjectCheckoutKeyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteProjectCheckoutKeyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteProjectCheckoutKey: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteProjectEnvVar deletes a project environment variable
*/
func (a *Client) DeleteProjectEnvVar(params *DeleteProjectEnvVarParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectEnvVarOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteProjectEnvVarParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteProjectEnvVar",
		Method:             "DELETE",
		PathPattern:        "/project/{project-slug}/envvar/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteProjectEnvVarReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteProjectEnvVarOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteProjectEnvVar: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProject gets a project
*/
func (a *Client) GetProject(params *GetProjectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetProjectParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProject",
		Method:             "GET",
		PathPattern:        "/project/{project-slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetProjectReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetProjectOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProject: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectCheckoutKey lists project checkout keys

Returns all checkout keys for this project.
*/
func (a *Client) GetProjectCheckoutKey(params *GetProjectCheckoutKeyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectCheckoutKeyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetProjectCheckoutKeyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProjectCheckoutKey",
		Method:             "GET",
		PathPattern:        "/project/{project-slug}/checkout-key/{fingerprint}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetProjectCheckoutKeyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetProjectCheckoutKeyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectCheckoutKey: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectEnvVar gets project environment variable

Returns a environment variable for this project.
*/
func (a *Client) GetProjectEnvVar(params *GetProjectEnvVarParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectEnvVarOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetProjectEnvVarParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProjectEnvVar",
		Method:             "GET",
		PathPattern:        "/project/{project-slug}/envvar/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetProjectEnvVarReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetProjectEnvVarOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectEnvVar: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ListProjectCheckoutKeys lists checkout keys

Returns all checkout keys for this project.
*/
func (a *Client) ListProjectCheckoutKeys(params *ListProjectCheckoutKeysParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListProjectCheckoutKeysOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListProjectCheckoutKeysParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListProjectCheckoutKeys",
		Method:             "GET",
		PathPattern:        "/project/{project-slug}/checkout-key",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListProjectCheckoutKeysReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListProjectCheckoutKeysOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ListProjectCheckoutKeys: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ListProjectEnvVars lists project environment variables

Returns all environment variables for this project.
*/
func (a *Client) ListProjectEnvVars(params *ListProjectEnvVarsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListProjectEnvVarsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListProjectEnvVarsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListProjectEnvVars",
		Method:             "GET",
		PathPattern:        "/project/{project-slug}/envvar",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListProjectEnvVarsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListProjectEnvVarsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ListProjectEnvVars: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
