// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ContextEnvVarInfo context env var info
//
// swagger:model ContextEnvVarInfo
type ContextEnvVarInfo struct {

	// ID of the context
	// Format: uuid
	ContextID strfmt.UUID `json:"context_id,omitempty"`

	// The date and time the environment variable was created
	// Example: 2023-02-10T04:49:36.117Z
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// The date and time the environment variable was last updated
	// Example: 2023-02-10T04:49:36.117Z
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`

	// The name of the environment variable
	Variable string `json:"variable,omitempty"`
}

// Validate validates this context env var info
func (m *ContextEnvVarInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContextID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContextEnvVarInfo) validateContextID(formats strfmt.Registry) error {
	if swag.IsZero(m.ContextID) { // not required
		return nil
	}

	if err := validate.FormatOf("context_id", "body", "uuid", m.ContextID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ContextEnvVarInfo) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ContextEnvVarInfo) validateUpdatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("updated_at", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this context env var info based on context it is used
func (m *ContextEnvVarInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ContextEnvVarInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContextEnvVarInfo) UnmarshalBinary(b []byte) error {
	var res ContextEnvVarInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
