// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrgLevelClaimsPayload org level claims payload
//
// swagger:model OrgLevelClaimsPayload
type OrgLevelClaimsPayload struct {

	// List of audience.
	// Required: true
	Audience []string `json:"audience"`

	// Time to live (JSON duration).
	// Example: 20d
	// Required: true
	TTL *string `json:"ttl"`
}

// Validate validates this org level claims payload
func (m *OrgLevelClaimsPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAudience(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTTL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrgLevelClaimsPayload) validateAudience(formats strfmt.Registry) error {

	if err := validate.Required("audience", "body", m.Audience); err != nil {
		return err
	}

	return nil
}

func (m *OrgLevelClaimsPayload) validateTTL(formats strfmt.Registry) error {

	if err := validate.Required("ttl", "body", m.TTL); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this org level claims payload based on context it is used
func (m *OrgLevelClaimsPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrgLevelClaimsPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrgLevelClaimsPayload) UnmarshalBinary(b []byte) error {
	var res OrgLevelClaimsPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
