// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProjectEnvVarInfo project env var info
//
// swagger:model ProjectEnvVarInfo
type ProjectEnvVarInfo struct {
	ProjectEnvVarPayload
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ProjectEnvVarInfo) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ProjectEnvVarPayload
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ProjectEnvVarPayload = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ProjectEnvVarInfo) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.ProjectEnvVarPayload)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this project env var info
func (m *ProjectEnvVarInfo) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ProjectEnvVarPayload
	if err := m.ProjectEnvVarPayload.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this project env var info based on the context it is used
func (m *ProjectEnvVarInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ProjectEnvVarPayload
	if err := m.ProjectEnvVarPayload.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectEnvVarInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectEnvVarInfo) UnmarshalBinary(b []byte) error {
	var res ProjectEnvVarInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
