// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProjectLevelClaimsPayload project level claims payload
//
// swagger:model ProjectLevelClaimsPayload
type ProjectLevelClaimsPayload struct {
	OrgLevelClaimsPayload
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ProjectLevelClaimsPayload) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 OrgLevelClaimsPayload
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.OrgLevelClaimsPayload = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ProjectLevelClaimsPayload) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.OrgLevelClaimsPayload)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this project level claims payload
func (m *ProjectLevelClaimsPayload) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with OrgLevelClaimsPayload
	if err := m.OrgLevelClaimsPayload.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this project level claims payload based on the context it is used
func (m *ProjectLevelClaimsPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with OrgLevelClaimsPayload
	if err := m.OrgLevelClaimsPayload.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectLevelClaimsPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectLevelClaimsPayload) UnmarshalBinary(b []byte) error {
	var res ProjectLevelClaimsPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
