// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProjectLevelClaimsInfo project level claims info
//
// swagger:model ProjectLevelClaimsInfo
type ProjectLevelClaimsInfo struct {
	OrgLevelClaimsInfo

	// The unique ID of the project.
	// Format: uuid
	ProjectID strfmt.UUID `json:"project_id,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ProjectLevelClaimsInfo) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 OrgLevelClaimsInfo
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.OrgLevelClaimsInfo = aO0

	// AO1
	var dataAO1 struct {
		ProjectID strfmt.UUID `json:"project_id,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.ProjectID = dataAO1.ProjectID

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ProjectLevelClaimsInfo) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.OrgLevelClaimsInfo)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		ProjectID strfmt.UUID `json:"project_id,omitempty"`
	}

	dataAO1.ProjectID = m.ProjectID

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this project level claims info
func (m *ProjectLevelClaimsInfo) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with OrgLevelClaimsInfo
	if err := m.OrgLevelClaimsInfo.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProjectID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProjectLevelClaimsInfo) validateProjectID(formats strfmt.Registry) error {

	if swag.IsZero(m.ProjectID) { // not required
		return nil
	}

	if err := validate.FormatOf("project_id", "body", "uuid", m.ProjectID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this project level claims info based on the context it is used
func (m *ProjectLevelClaimsInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with OrgLevelClaimsInfo
	if err := m.OrgLevelClaimsInfo.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectLevelClaimsInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectLevelClaimsInfo) UnmarshalBinary(b []byte) error {
	var res ProjectLevelClaimsInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
